### PR TITLE
Add karate integration

### PR DESCRIPTION
**Pull request by baev**
### Context

Adds karate framework https://github.com/intuit/karate integration

fixes https://github.com/allure-framework/allure-java/issues/540 https://github.com/allure-framework/allure2/issues/1061

TODO:

- [x] Support base scenarios
- [x] Support for steps
- [ ] Support for embeddings
- [ ] Support for request & response attachments
- [ ] Support for backgrounds
- [x] Support for examples
- [ ] Allure API exposed - custom report metadata
- [ ] Allure History Support: history id / test case id
- [ ] Allrue TestOps integration (selective runs, allure id)

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by krmahadevan** [comment]
@baev - Are there plans on getting this implemented? Are you looking for any help ? I can try and contribute, if you could please help let me know what all things are still pending. I do see the list of items that are to be done, but my knowledge about allure is pretty basic and so I would need a bit of hand holding :)

**Comment by pavlo-sv** [comment]
@baev, any updates on Karate DSL support?

**Comment by pavlo-sv** [comment]
hi @baev, I'm currently working with the latest version of Karate DSL and could help you with implementing and testing the integration.
Please let know if you need any support to speed up the feature.

Thanks!

**Comment by baev** [comment]
@pavlo-sv awesome! It's been a while since I started my work on this and I have no time to finish the task. Feel free to pick use this branch as a baseline for your work or you can implement allure-karate integration from the scratch if you want. I'll be happy to review it and give you some advice if you need any

**Comment by QATew** [comment]
What is the status on this? Any plan to have it deployed?

**Review by QATew — APPROVED** [review]

**Comment by QATew** [comment]
@npolyakova  Anything we can do to help you with this plugin?

**Review by eroshenkoam — APPROVED** [review]

**Pull request merged**
