### PR TITLE
Add support for Spock 2

### LINKED ISSUE #239: Support when/then Spock annotations
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Allure doesn't support when/then steps from Spock (bdd framework)

#### What is the expected behavior?
To see bdd steps from Spock specs in Allure reports

#### What is the motivation / use case for changing the behavior?
test analyst and manual QAs will able to see what happens in automation tests without reading full log with some technical information

#### Please tell us about your environment:
Jenkins+maven+java+geb+spock

| Allure version | 2.19.0 |
| --- | --- |
| Test framework | JUnit@4.12 |
| Allure integration | allure-spock@2.7.0 |
| Generate report using | allure-maven@2.9 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

### LINKED ISSUE #510: Add support for spock 2.0 versions
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Currently allure supports spock 1.3 version

#### What is the motivation / use case for changing the behavior?
Spock 2.0 uses junit5, supports parallel test running, groovy 3.0 and other useful features. I use 2.0-M4-groovy-3.0 version and it's incompatible with allure-spock.

#### Please tell us about your environment:

| Allure version | 2.13.6 |
| --- | --- |
| Test framework | spock@2.0-M4-groovy-3.0 |
| Allure integration | allure-spock@2.13.6 |
| Generate report using | allure-gradle@2.8.1 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

### PR DESCRIPTION
**Pull request by baev**
### Context

fixes #510 (closes #830)
fixes #239 (closes #429)

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Review by eroshenkoam — APPROVED** [review]

**Comment by baev** [comment]
Summon @Guter1988

**Comment by vladciolte** [comment]
Hello, 

Do you know when this will be released? 

Thank you

**Comment by baev** [comment]
after this one is merged https://github.com/allure-framework/allure-java/pull/840

**Comment by Guter1988** [comment]
Hi @baev,
I hope you are well and all good ))

I have a question -
At the new module Spock2, I'm using it and can see some issues with ignoring test cases.
They are not written in the report at all.
For example, when using the Junit5 module, they are shown as ignoring and gray tests. But when using Spock2, they are not shown at all in the report.

How can we fix it? What can be a workaround?

**Comment by baev** [comment]
please use https://github.com/orgs/allure-framework/discussions for questions

**Pull request merged**
