### PR TITLE
Use blocking io for results write

### LINKED ISSUE #197: [allure-testng] Could not write Allure test result
from https://github.com/allure-framework/allure2/issues/738

[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
In my testcase,if run failed,it will throw AllureResultsWriteException

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.12 |
| Allure adaptor | allure-testng@2.0-BETA21 |
| Generate report using | allure-maven@2.19 |

#### Other information
 `
 io.qameta.allure.AllureResultsWriteException: Could not write Allure test result
 `
 `
	at io.qameta.allure.FileSystemResultsWriter.write(FileSystemResultsWriter.java:43)
 `
 `
	at io.qameta.allure.AllureLifecycle.lambda$writeTestCase$12(AllureLifecycle.java:197)
 `
 `
	at java.util.Optional.ifPresent(Optional.java:159)
 `
 `
	at io.qameta.allure.AllureLifecycle.writeTestCase(AllureLifecycle.java:195)
 `
 `
	at io.qameta.allure.testng.AllureTestNg.onTestFailure(AllureTestNg.java:260)
 `
 `
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1738)
  `
 `
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1722)
  `
 `
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1258)
  `
 `
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
 `
 `
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
 `
 `
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 `
 `
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 `
 `
	at java.lang.Thread.run(Thread.java:748)
 `
 `
Caused by: java.nio.channels.ClosedByInterruptException
  `
 `
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
 `
 `
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:216)
  `
 `
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
 `
 `
	at java.nio.channels.Channels.writeFully(Channels.java:101)
 `
 `
	at java.nio.channels.Channels.access$000(Channels.java:61)
  `
 `
	at java.nio.channels.Channels$1.write(Channels.java:174)
 `
 `
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2085)
  `
 `
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.close(UTF8JsonGenerator.java:1127)
 `
 `
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3898)
  `
 `
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3164)
  `
 `
	at io.qameta.allure.FileSystemResultsWriter.write(FileSystemResultsWriter.java:41)
 `
 `
	... 12 more
`

### PR DESCRIPTION
**Pull request by baev**
fixes #197

https://github.com/AutomatedOwl/allure-testng-result-write-bug used to check the fix

### CODE REVIEW

**Comment by AvrahamAtia** [comment]
What time  this PR will be merge?

**Comment by AvrahamAtia** [comment]
@baev Ok, Thanks allot!

**Comment by AutomatedOwl** [comment]
@baev  thanks for the effort !

**Comment by AvrahamAtia** [comment]
@baev NP:)

**Comment by alekseyp555** [comment]
I've the same issue
java.lang.NoSuchMethodError: io.qameta.allure.model.TestResult.setStatus(Lio/qameta/allure/model/Status;)
when a new fixed build will be available?

**Pull request merged**
