### PR TITLE
[httpclient] Don't consume HTTP responses

### PR DESCRIPTION
**Pull request by TobiX**
### Context

Since the `LoggableEntity` defined in `AllureHttpClientResponse` doesn't overwrite all methods of `HttpEntityWrapper`, there are code paths around it, which modifies the behaviour of response objects when this interceptor is attached to the HTTP client. I noticed this with code which was using `BufferedHttpEntity` when reading from the responce and running into "Stream already consumed" errors...

This change does away with the custom entity wrapper and uses `BufferedHttpEntity`, which is designed for exactly this usecase. As an additional optimization, we don't replace the `HttpEntity` at all if the returned entity is already "repeatable".

#### Checklist
- [X] [Sign Allure CLA][cla]
- [X] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by TobiX** [comment]
Something I noticed here: Is it a good idea to preserve requests/responses of any size? Maybe add a default limit to ~100kB, so the user won't shoot himself in the foot if tests contain large requests/responses?

**Comment by TobiX** [comment]
@baev Ping? I cannot fix the one failing check because I cannot change labels on the issue.

**Review by baev — APPROVED** [review]

**Comment by baev** [comment]
closed & reopened to trigger actions

**Comment by baev** [comment]
> Is it a good idea to preserve requests/responses of any size? Maybe add a default limit to ~100kB, so the user won't shoot himself in the foot if tests contain large requests/responses?

Yeah, thats actually sounds right. It would be a nice to have a possibility to configure body size limit with some suitable defaults. Feel free to provide a PR with that change ;)

**Comment by baev** [comment]
@TobiX thanks!

**Pull request merged**
