### PR TITLE
Update AllureSpock.java for Spock V2 and above 

### LINKED ISSUE #510: Add support for spock 2.0 versions
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Currently allure supports spock 1.3 version

#### What is the motivation / use case for changing the behavior?
Spock 2.0 uses junit5, supports parallel test running, groovy 3.0 and other useful features. I use 2.0-M4-groovy-3.0 version and it's incompatible with allure-spock.

#### Please tell us about your environment:

| Allure version | 2.13.6 |
| --- | --- |
| Test framework | spock@2.0-M4-groovy-3.0 |
| Allure integration | allure-spock@2.13.6 |
| Generate report using | allure-gradle@2.8.1 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

### PR DESCRIPTION
**Pull request by Guter1988**
### Context

This is a fix for Spock version 2 and above

fixes #510

#### Checklist
- [x] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by Guter1988** [comment]
Hello @baev 
Can you please take a look and this pull request? This is a fix for the Spock version above 2

**Comment by baev** [comment]
@Guter1988 could you please fix the build?

**Comment by Guter1988** [comment]
@baev On it

**Comment by baev** [comment]
@Guter1988 build failure

**Comment by Guter1988** [comment]
@baev I saw. Thanks.
Added `@SuppressWarnings("unchecked")`
Let's see now

**Comment by Guter1988** [comment]
@baev All passed? Need to review now?

**Comment by baev** [comment]
@Guter1988 I did additional research and since spock2 is based on top of junit-platform we need to introduce separate module for spock2 integration so we can test it properly. 

Let me take this task from here, you may expect a new release with support for spock2 later this week 

Thanks for all the work anyway

**Comment by Guter1988** [comment]
Thank you @baev

**Pull request closed without merging**
