### PR TITLE
fix(allure-scalatest): cross-build for scala 2.12 and 2.13

### PR DESCRIPTION
**Pull request by baev**
#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by atais** [comment]
Great job! Thanks for fixing the missing parts!

🎆 🍾 

please, dont forget to release the fixed scalatest version asap 😉 

I will cancel my PR

**Comment by prokod** [comment]
I have created a test similar to this PR to try and achieve the same, having `<name>_2.13-<version>-<classifier>` and I was not able. So currently scala cross compiling  documentation stating limitation for creating scaladoc, sources for the crossed compiled artifacts still stands

**Comment by baev** [comment]
@prokod, please see the final version in the main repo. You need to apply two more fixes:

1) https://github.com/allure-framework/allure-java/pull/1111
2) https://github.com/allure-framework/allure-java/commit/b40acffa5d4de4257f7420152b050b60c5e15828

After that, the release was accepted by Sonatype and successfully added to Maven Central, see https://mvnrepository.com/artifact/io.qameta.allure/allure-scalatest

**Comment by prokod** [comment]
@baev with the additional code changes it makes now sense. Thx for pointing me to that.

**Pull request merged**
