### PR TITLE
Fixes #849 Cucumber 4.x Parallel Support

### PR DESCRIPTION
**Pull request by james-bjss**
### Context
See:
https://github.com/allure-framework/allure2/issues/849#

NB. I know this is not ready to be merged, but wanted to start a discussion about how to fix.
#### Checklist
- [X] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by james-bjss** [comment]
**I am aware that the above is not good to merge, but wanted to start the discussion on the approach to resolve this issue For now I just duplicated the cucumber3 module, but I am aware it can be refactored to avoid this code duplication.**

@letsrokk sharing the solution I trialled.

I have tested the above with my projects and it appears to work fine; however I am aware that the sourceUtils class copied form the cucumber code may not be threadsafe.

Also: One issue I noticed is all my tests were marked as 'Flaky' when executing under TestNg, not sure if this is related, but will investigate.

**Comment by letsrokk** [comment]
@james-bjss thanks! I'll have a look into your commits shortly. 

Just FYI, I started work on adapting adapter (😄) for Cucumber JVM 4.x, but as you have mentioned, we do have bits from cucumber code base in there. I want to get rid of it, and make code duplication a little as possible (there's a lot of dups between 2.x - 3.x - 4.x adapters)

**Comment by james-bjss** [comment]
Hi, no proble.. Thanks for takibg time to work on this!

If I can help then please let me know, even if its just testing or documentation.

Also it seem intellij has a similar problem :)
See: https://youtrack.jetbrains.com/issues?q=by%3A+me

**Comment by letsrokk** [comment]
Yeah, IDEA plugin uses same approach of implementing Formatter plugin to capture progress. Maybe be a good idea  to look into their implementation to see how they solved problem with access to Cucumber API

**Comment by timtebeek** [comment]
Nice to see the work being done here; Slightly odd request perhaps: can you add a test similar to this one? https://github.com/allure-framework/allure-java/pull/262/files
I'd need --dry-run support for a plugin of ours: https://github.com/allure-framework/allure-java/issues/255

**Comment by letsrokk** [comment]
@james-bjss hey, James
I have been going through some options and variants, but couldn't find a nice and clean way to reduce amount of code duplication due to changes in internals ofCucumber itself. 

So, for now we can go with copy-paste strategy, I guess.

I have a half-ready branch, just need to clean up some things and finish tests before creating a pull-request

**Comment by james-bjss** [comment]
> @james-bjss hey, James
> I have been going through some options and variants, but couldn't find a nice and clean way to reduce amount of code duplication due to changes in internals of Cucumber itself.
> 
> So, for now we can go with copy-paste strategy, I guess.
> 
> I have a half-ready branch, just need to clean up some things and finish tests before creating a pull-request

Cool, yeah, I was thinking about ways to do it but struggled too. Can I take a peek at your branch?

**Comment by letsrokk** [comment]
@james-bjss yeah, it's in my fork on [github here](https://github.com/letsrokk/allure-java/tree/cucumber-jvm-4), but it still missing a few things that are not commited yet. I have pushed mostly only tests and minor changes so far

**Pull request closed without merging**
