### PR TITLE
Add hamcrest integration

### PR DESCRIPTION
**Pull request by a-simeshin**
### Context
Adds hamcrest library integration https://github.com/hamcrest/JavaHamcrest
Docs http://hamcrest.org/JavaHamcrest/tutorial

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by a-simeshin** [comment]
@baev Hi there! 
Would you be so nice to suggest a solution to this problem?
```
[Misc | NewlineAtEndOfFile] io.qameta.allure.hamcrest.(AllureHamcrestAssert.java:1)
  File does not end with a newline.
  http://checkstyle.sourceforge.io/config_misc.html#NewlineAtEndOfFile
```

Also could I fix this ⬇️ and this ⬆️ in the one commit? 
```
[Imports | AvoidStarImport] io.qameta.allure.hamcrest.(AllureHamcrestAssert.java:4)
  Using the '.*' form of import should be avoided - org.aspectj.lang.annotation.*.
  http://checkstyle.sourceforge.io/config_imports.html#AvoidStarImport
```

**Comment by baev** [comment]
And what is the problem, exactly? 

To fix first problem you should add a new line at the end of `AllureHamcrestAssert` file, for second problem just expand wildcard import (all IDE's have a context action for that).

**Comment by a-simeshin** [comment]
> And what is the problem, exactly?
> 
> To fix first problem you should add a new line at the end of `AllureHamcrestAssert` file, for second problem just expand wildcard import (all IDE's have a context action for that).

Thanks for the explanation! Unfortunately, I am simply not familiar with the first problem. I`ll fix both problems soon

**Comment by a-simeshin** [comment]
> And what is the problem, exactly?
> 
> To fix first problem you should add a new line at the end of `AllureHamcrestAssert` file, for second problem just expand wildcard import (all IDE's have a context action for that).

The problem was the lack of .gitattributes that spotlessApply works with. Of course, plugin took the system eol = CRLF.
With ``* text eol = lf`` everything worked like a charm.

Done, ready for review.

**Review by baev — APPROVED** [review]

**Comment by baev** [comment]
good job 👍

**Pull request merged**
