### PR TITLE
Handle tests with PENDING steps (PendingException) as skipped 

### PR DESCRIPTION
**Pull request by letsrokk**
[//]: # (
. Thank you so much for sending us a pull request! 
.
. Make sure you have a clear name for your pull request. 
. The name should start with a capital letter and no dot is required in the end of the sentence.
. To link the request with isses use the following notation: (fixes #123, fixes #321\)
.
. An example of good pull request names:
. - Add Russian translation (fixes #123\)
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

### Context
[//]: # (
Describe the problem or feature in addition to a link to the issues
)

As is right now, tests with PENDING steps (which throw cucumber.api.PendingException) are marked as PASSED (ex. on screenshot) with steps remaining in running status.
PASSED test with PENDING step

We can handle such steps the same way as failed steps but with marking tests as SKIPPED instead of PASSED
SKIPPED test with PENDING steps

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by baev** [comment]
@clicman could you please review?

**Comment by clicman** [comment]
@letsrokk hi! Test case which has passed steps cannot be marked as skipped. The only fully skipped test case should me marked as skipped otherwise it should be passed.

**Comment by baev** [comment]
> Test case which has passed steps cannot be marked as skipped. The only fully skipped test case should me marked as skipped otherwise it should be passed.

not sure that it is true. I mean if I only implement the first step the test is still checks nothing. And also there is may be a case when you perform some steps to check is the test should be run or not.

**Comment by letsrokk** [comment]
@clicman I agree that 'skipped' status is not the most accurate way to describe test with some unimplemented, but it definetly should not be considered as 'passed' test.

Allure Report has another status - 'unknown' (purple colored) - maybe we can use this type of marking instead of 'skipped'? 

Or one more option. If I remember correctly, Allure 1.x had 'pending' status in report. Maybe we can introduce it back into Allure 2.0?

**Comment by baev** [comment]
Pending status means that test was not run (it is execution status, like `not implemented`, `scheduled`, `running`, `finished`, `interrupted`, `pending` etc). I guess the full support of execution statuses will be introduced with Allure 3 together with realtime reporting feature. So in terms of Allure 3 it should be `unknown` result status + `not implemented` (or `pending`) execution status. At the moment I suggest you to use `skipped` for such case

**Comment by clicman** [comment]
Okay. Agree. Let it be skipped for now and will be changed later.

**Comment by clicman** [comment]
@baev yes, all good. LGTM.

**Comment by baev** [comment]
@letsrokk @clicman thanks!

**Pull request merged**
