### PR TITLE
Addressed issue #593 - Link TestResult to JUnit platform TestIdentifier

### PR DESCRIPTION
**Pull request by naresha**
#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by baev** [comment]
We can't use uniqueId as testCaseId as it will break parameterised tests: uniqueId is differ for different parameters but testCaseId should be the same no matter what parameter values are provided.

So far Allure has: 
* `testCaseId` (same for the same test cases, used in Allure TestOps to determinate test cases). If not specified, `md5(fullName)` is used.
* `historyId` (aka `historyKey`): used for determinate retries within a test run. In case of same `historyId` results are merged, and only the last one is shown.  If not specified, calculated as `md5(testCaseId, parameterValues, environment)`

**Comment by naresha** [comment]
Thanks for sharing the details of testCaseId.
Do you have any suggestions on alternative ways to pass unique id?

**Comment by baev** [comment]
simply put it into labels, you can pick any key you like, for example `JUNIT5_UNIQUE_ID`

**Comment by naresha** [comment]
Thanks for your suggestion.

**Review by baev — APPROVED** [review]

**Comment by baev** [comment]
@naresha thanks!

**Pull request merged**
