### PR TITLE
Add support for Cucumber 7

### PR DESCRIPTION
**Pull request by jsa34**
### Context
Cucumber 7 is currently not supported, but is released as a stable release with Cucumber JVM 7.
Resolves: #684 

#### Checklist
- [X] [Sign Allure CLA][cla]
- [X] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by jsa34** [comment]
Hello! 

@baev (or anyone else with powers!) Would you be able to give this a code review?

Thank you :)

**Review by baev — APPROVED** [review]

**Comment by jsa34** [comment]
Thanks, @baev ! 

Do you know when a new release is likely to be made?

**Comment by baev** [comment]
I think you can expect one by the end of the week

**Comment by jsa34** [comment]
Fab!  Thanks once again!

**Comment by jsa34** [comment]
Hello!  Apologies for the bump - any update on release date? :)

**Comment by nir-tal-talkspace** [comment]
Hello - when will allure-cucumber7-jvm be available on maven central? 

Thanks!

**Comment by baev** [comment]
> allure-cucumber7-jvm be available on maven central?

it is already https://repo1.maven.org/maven2/io/qameta/allure/allure-cucumber7-jvm/2.17.0/

**Pull request merged**
