### PR TITLE
fix(allure-karate): fix duplicate scenarios when call or callonce keywords are used

### PR DESCRIPTION
**Pull request by umitozdemirf**
## Problem
- Steps like `call` and `callonce` were being treated as separate test scenarios.
- This was inflating the test count in Allure and making the reports harder to read.

## Solution
1. **Locate the Issue:**
   - Found that the issue was in the `beforeStep` and `afterStep` methods in the `AllureKarate` class.

2. **Update `beforeStep`:**
   - Added a check to skip steps that start with `call` or `callonce`:
     ```java
     @Override
     public boolean beforeStep(final Step step, final ScenarioRuntime sr) {
         final String parentUuid = (String) sr.magicVariables.get(ALLURE_UUID);
         if (Objects.isNull(parentUuid)) {
             return true;
         }

         // Skip 'call' and 'callonce' steps
         if (step.getText().startsWith("call") || step.getText().startsWith("callonce")) {
             LOGGER.info("Skipping Allure for call/callonce: " + step.getText());
             return true;
         }

         final String uuid = parentUuid + "-" + step.getIndex();
         final io.qameta.allure.model.StepResult stepResult = new io.qameta.allure.model.StepResult()
                 .setName(step.getText());
         lifecycle.startStep(parentUuid, uuid, stepResult);

         return true;
     }
     ```

3. **Update `afterStep`:**
   - Also skipped these steps in `afterStep` to avoid processing them as separate tests:
     ```java
     @Override
     public void afterStep(final StepResult result, final ScenarioRuntime sr) {
         final String parentUuid = (String) sr.magicVariables.get(ALLURE_UUID);
         if (Objects.isNull(parentUuid)) {
             return;
         }

         final Step step = result.getStep();

         // Skip 'call' and 'callonce' steps
         if (step.getText().startsWith("call") || step.getText().startsWith("callonce")) {
             LOGGER.info("Skipping Allure for call/callonce: " + step.getText());
             return;
         }

         final String uuid = parentUuid + "-" + step.getIndex();
         final Result stepResult = result.getResult();

         final Status status = !stepResult.isFailed()
                 ? Status.PASSED
                 : Optional.of(stepResult)
                         .map(Result::getError)
                         .flatMap(ResultsUtils::getStatus)
                         .orElse(null);

         final StatusDetails statusDetails = Optional.of(stepResult)
                 .map(Result::getError)
                 .flatMap(ResultsUtils::getStatusDetails)
                 .orElse(null);

         lifecycle.updateStep(uuid, s -> {
             s.setStatus(status);
             s.setStatusDetails(statusDetails);
         });
         lifecycle.stopStep(uuid);
     }
     ```

4. **Test the Fix:**
   - After these changes, I tested the setup, and the `call` and `callonce` steps now show up as part of the parent scenario, not as separate tests.

## Result
- Test counts in Allure are accurate now.
- Reports look much cleaner and more understandable.

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Review by baev — CHANGES_REQUESTED** [review]
please add a test & sign CLA

**Comment by umitozdemirf** [comment]
@baev I added tests and fix commit user, thank you.

**Comment by baev** [comment]
@umitozdemirf great job 👍, thanks. 

I would like to have spearate tests for `call` and `callonce` features as well as a test that checks the results metadata when `call` or `callonce` is used (you need to make sure all the steps are displayed correctly, no metadata is duplicated etc).

Feel free to provide an additional PR with such improvements!

**Review by baev — APPROVED** [review]

**Comment by umitozdemirf** [comment]
Thank you @baev

**Pull request merged**
