### PR TITLE
AllureSelenide configuration for screenshots and page source

### PR DESCRIPTION
**Pull request by simple-elf**
[//]: # (
. Thank you so much for sending us a pull request! 
.
. Make sure you have a clear name for your pull request. 
. The name should start with a capital letter and no dot is required in the end of the sentence.
. To link the request with isses use the following notation: (fixes #123, fixes #321\)
.
. An example of good pull request names:
. - Add Russian translation (fixes #123\)
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

### Context
[//]: # (
Describe the problem or feature in addition to a link to the issues
)
Added configuration for save screenshots and page sources to Allure report or not.

```
SelenideLogger.addListener("AllureSelenide", new AllureSelenide().screenshots(true).savePageSource(false));
```

#### Checklist
- [x] [Sign Allure CLA][cla]

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by simple-elf** [comment]
Also changes in allure-docs https://github.com/allure-framework/allure-docs/pull/93

**Comment by baev** [comment]
@simple-elf please fix the build

**Comment by baev** [comment]
@simple-elf thanks!

**Comment by rosolko** [comment]
@simle-elf @baev  This PR override configuration from Selenide config. 
So if I’m set config in any other place this listener override it. 
I think that better solution will be direct:
1. Create 2 constructors - empty and with two current params 
2. Do nothing in empty constructor
3. Update Selenide configuration inside all arg constructor and remove class fields. 
4. In code(on event) look for configuration value, so both behaviors will work. Default from selenide and user defined. And custom listener config.

**Comment by rosolko** [comment]
@simple-elf @baev 
I mean something like that:
```
public class AllureSelenide implements LogEventListener {
    private final AllureLifecycle lifecycle;

    public AllureSelenide() {
        this(Allure.getLifecycle());
    }

    public AllureSelenide(final AllureLifecycle lifecycle) {
        this.lifecycle = lifecycle;
    }

    public AllureSelenide screenshots(final boolean saveScreenshots) {
        Configuration.screenshots = saveScreenshots;
        return this;
    }

    public AllureSelenide savePageSource(final boolean savePageHtml) {
        Configuration.savePageSource = savePageHtml;
        return this;
    }

    @Override
    public void onEvent(final LogEvent event) {
                ...
                if (Configuration.screenshots) {
                    lifecycle.addAttachment("Screenshot", "image/png", "png", getScreenshotBytes());
                }
                if (Configuration.savePageSource) {
                    lifecycle.addAttachment("Page source", "text/html", "html", getPageSourceBytes());
                }
                ...
    }
```

**Comment by simple-elf** [comment]
Like I said in https://github.com/allure-framework/allure-java/pull/198 with selenide screenshots configuration files will be dublicates in allure-results folder and in selenide folder fo screenshots (and page htmls). For using this integration you need to set `Configuration.screenshots = false` - and you will get screenshots in allure-results.

**Pull request merged**
