### PR TITLE
Bump cucumberjvm

### PR DESCRIPTION
**Pull request by jsa34**
[//]: # (
. Thank you so much for sending us a pull request! 
.
. Make sure you have a clear name for your pull request. 
. The name should start with a capital letter and no dot is required in the end of the sentence.
. To link the request with isses use the following notation: (fixes #123, fixes #321\)
.
. An example of good pull request names:
. - Add Russian translation (fixes #123\)
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

### Context
[//]: # (
Describe the problem or feature in addition to a link to the issues
)

#### Checklist
- [X] [Sign Allure CLA][cla]
- [X] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by baev** [comment]
@jsa34 build is failed because of api change

**Comment by jsa34** [comment]
@baev aha - panicked because I wasn't expecting a fail!

**Comment by baev** [comment]
@jsa34 don't worry, I'm updating other deps at the moment and can fix it by myself

Thanks anyway

**Comment by baev** [comment]
fixed via https://github.com/allure-framework/allure-java/pull/320

**Pull request closed without merging**
