### PR TITLE
Add support for fixtures for spock2

### LINKED ISSUE #839: Does Allure can add from Spock Setup/SetupSpec cleanup/cleanupSpec as JUnit Before/After
## Description
I want to ask if there is an option to add Set up and tear down when using the Spock testing framework.
I found this option exists from Junit/TestNG and other frameworks, but I cannot see this option for Spock.

## Motivation and Context
To be able to see in the report the setup and tear down the story as well.

## current behavior
Only tests (def "<String>") are shown in the report.
 
## Version that used
allure.version - 2.16.1
Spock-framework.version - 2.0-groovy-3.0

Thank you ahead

### PR DESCRIPTION
**Pull request by baev**
### Context

fixes #839

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Review by eroshenkoam — APPROVED** [review]

**Comment by baev** [comment]
this one isn't working correctly. We should intercept fixture methods instead of phase:

```java
 spec.getAllFixtureMethods().forEach(methodInfo -> {
            if (methodInfo.getKind().isSpecScopedFixtureMethod()) {
                methodInfo.addInterceptor(specFixtureInterceptor);
            }
            if (methodInfo.getKind().isFeatureScopedFixtureMethod()) {
                methodInfo.addInterceptor(featureFixtureInterceptor);
            }
        });
```

**Comment by Guter1988** [comment]
Hello @baev,

I start to use new Spock2 dependency :))

One issue I can see after running on Jenkins I got this error:
`Could not read test result file /root/workspace/Production_Validation_Odata_PTA/allure-results/2a5a3305-e43c-4eb6-8440-44ef0a47159e-result.json
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "testCaseName" (class io.qameta.allure.model.TestResult), not marked as ignorable (18 known properties: "start", "descriptionHtml", "parameters", "name", "historyId", "statusDetails", "status", "links", "fullName", "uuid", "description", "testCaseId", "stage", "labels", "stop", "steps", "rerunOf", "attachments"])
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 157] (through reference chain: io.qameta.allure.model.TestResult["testCaseName"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
	at io.qameta.allure.allure2.Allure2Plugin.readTestResult(Allure2Plugin.java:344)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.qameta.allure.allure2.Allure2Plugin.readResults(Allure2Plugin.java:104)
	at io.qameta.allure.ReportGenerator.lambda$readResults$0(ReportGenerator.java:47)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.qameta.allure.ReportGenerator.readResults(ReportGenerator.java:47)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:69)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
	at io.qameta.allure.Commands.generate(Commands.java:104)
	at io.qameta.allure.CommandLine.run(CommandLine.java:152)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at io.qameta.allure.CommandLine.main(CommandLine.java:88)`

First, it can be related to the new version. Second, what can fix it? (Allure Jenkins plugin?)

**Comment by baev** [comment]
You need to upgrade Allure Commandline tool to latest version as well

**Comment by Guter1988** [comment]
I have updated the Jenkins slave manually to the new version, 2.20.0, and now all is working great.
Thanks

**Pull request merged**
